//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSur.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class arma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arma()
        {
            this.paisArma = new HashSet<paisArma>();
        }
    
        public long id_arma { get; set; }
        public string nombre { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> cantidadMunicion { get; set; }
        public Nullable<long> IdTipoArma_Fk { get; set; }
        public Nullable<long> IdMarca_Fk { get; set; }
    
        public virtual marca marca { get; set; }
        public virtual tipoArma tipoArma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paisArma> paisArma { get; set; }
    }
}
