//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSur.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class soldado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soldado()
        {
            this.arsenalSoldado = new HashSet<arsenalSoldado>();
            this.soldadoTipoArma = new HashSet<soldadoTipoArma>();
        }
    
        public long id_soldado { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> experiencia { get; set; }
        public Nullable<int> capacidadCarga { get; set; }
        public Nullable<long> idPais_Fk { get; set; }
        public Nullable<long> idProfesion_Fk { get; set; }
        public Nullable<long> idRango_Fk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arsenalSoldado> arsenalSoldado { get; set; }
        public virtual pais pais { get; set; }
        public virtual profesion profesion { get; set; }
        public virtual rango rango { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soldadoTipoArma> soldadoTipoArma { get; set; }
    }
}
