//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSur.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public long id_usuario { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<long> id_tipoUsuario { get; set; }
    
        public virtual tipoUsuario tipoUsuario { get; set; }
    }
}
